---
services:
  ark-server:
    image: indifferentbroccoli/ark-server-docker:latest
    platform: linux/amd64
    restart: unless-stopped
    container_name: ark-server
    stop_grace_period: 30s
    ports:
      - 27960:27960/udp
      - 27960:27960/tcp
      - 27961:27961/udp
      - 27961:27961/tcp
      - 27962:27962/udp
      - 27962:27962/tcp
      - 27963:27963/tcp
    env_file:
      - .env
    volumes:
      - ./steamcmd/ark:/home/steam/steamcmd/ark